# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='geom',
            new_name='mpoly',
        ),
    ]
