# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_context_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='context',
        ),
    ]
