# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20160708_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
