# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_geostatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geostatus',
            name='name',
        ),
        migrations.AddField(
            model_name='geostatus',
            name='location',
            field=models.CharField(default='Unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geostatus',
            name='verb',
            field=models.CharField(default='Unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geostatus',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
